### ISSUE TITLE
every session becomes a remember session when REMEMBER_COOKIE_REFRESH_EACH_REQUEST is set

### ISSUE THREAD

**Issue by RazerM** [maxcountryman/flask-login#424] opened 2019-03-22 13:14 UTC
**Describe the bug**
A user is logged in with `remember=False`. If the app is configured with `REMEMBER_COOKIE_REFRESH_EACH_REQUEST`, the remember cookie gets set anyway.

**To Reproduce**
1. Add `REMEMBER_COOKIE_REFRESH_EACH_REQUEST = True` to the flask configuration.
2. Call `login_user(..., remember=False)`
3. Verify that the remember cookie was set anyway.

**Expected behavior**
The remember cookie should not be set if the user was logged in with `remember=False`

**Additional context**

This seems to be the culprit:

https://github.com/maxcountryman/flask-login/blob/486c456907e307e363d0c334fb2c079d4fa25d55/flask_login/login_manager.py#L422-L424

The code below that calls `_set_cookie` which sets the remember cookie.

**Comment by RazerM** [comment] 2019-06-05 15:25
@maxcountryman I can submit a PR if you agree with the expected behaviour I wrote above

**Comment by maxcountryman** [comment] 2019-06-05 15:29
@alanhamlett any thoughts on this?

**Comment by HUSSTECH** [comment] 2020-01-29 19:13
@RazerM I think is right, and that this is a bug. This feature was introduced in #359 and from reading the PR or the code, I think the behaviour we see is probably unintended.

Rightly pointed out in the snippet from `login_manager.py`, when `REMEMBER_COOKIE_REFRESH_EACH_REQUEST` is set...

https://github.com/maxcountryman/flask-login/blob/486c456907e307e363d0c334fb2c079d4fa25d55/flask_login/login_manager.py#L420-L434

L422-424
```python
if 'remember' not in session and \ 
             current_app.config.get('REMEMBER_COOKIE_REFRESH_EACH_REQUEST'): 
         session['remember'] = 'set' 
```
will only enter when the `remember` key is not found in the session dictionary. The issue is that due to the `pop()` command on L427
```python
operation = session.pop('remember', None)
```
they key will always be cleared/removed from the session dict. A missing/empty `remember` key is also the state of things when users have selected to not "Remember Me", therefore, this `if` is *always* entered when `REMEMBER_COOKIE_REFRESH_EACH_REQUEST` is set.

On quick glance, a rough idea could be to refactor to something like this
```python
    def _update_remember_cookie(self, response):
        # Don't modify the session unless there's something to do.

        if 'remember' in session or \
                current_app.config.get('REMEMBER_COOKIE_REFRESH_EACH_REQUEST'):
            operation = session.pop('remember', None)

            if operation == 'set' and 'user_id' in session:
                self._set_cookie(response)
            elif operation == 'clear':
                self._clear_cookie(response)
            elif 'user_id' in session and \ 
                     current_app.config.get('REMEMBER_COOKIE_REFRESH_EACH_REQUEST'):
                self._set_cookie(response)

        return response
```
this option at least preserves the "fast" path when  `REMEMBER_COOKIE_REFRESH_EACH_REQUEST=False` and thus minimises time in this function.

**Comment by maxcountryman** [comment] 2020-02-12 14:51
A PR would be helpful, but I think more importantly a test.

**Comment by maxcountryman** [comment] 2020-02-15 16:20
Closing for now. Please feel free to address with a PR.

**Comment by RazerM** [comment] 2020-02-15 17:55
Why was this issue closed? I've submitted a PR with a failing test.

**Comment by maxcountryman** [comment] 2020-02-15 18:06
Thanks! I hadn’t seen that so I’ll reopen.

**Comment by gimbo** [comment] 2020-04-06 12:01
@RazerM Where is that PR? I've just come across this bug today so was curious, but I can't see the PR (though I can see the commit on your fork).

**Comment by RazerM** [comment] 2020-04-06 12:02
@gimbo https://github.com/maxcountryman/flask-login/pull/473

**Comment by RazerM** [comment] 2020-04-06 12:02
@gimbo https://github.com/maxcountryman/flask-login/pull/473

**Closed** 2022-03-30 16:50 UTC
