### ISSUE TITLE
Flask clients share current_user !

### ISSUE THREAD

**Issue by couchounou** [maxcountryman/flask-login#722] opened 2022-12-10 09:25 UTC
I have a **unvolontary sharing of "current_user"** for  **ALL logged users** after upgrading my app from flask 0.6.1 to 0.6.2...so urgently revert back  to 0.6.1.
Also "remenber cookies" has been shared ... so i had to change server key to killl all remenber cookies...

Running on 
Flask==2.1.2
Werkzeug==2.0.2

still happend on flask 2.2

_Originally posted by @couchounou in https://github.com/maxcountryman/flask-login/issues/721#issuecomment-1345189364_

**Comment by davidism** [comment] 2022-12-10 13:02
Duplicate of #721

**Closed by davidism** 2022-12-10 13:02 UTC
