### ISSUE TITLE
User's session highjacking when running with gunicorn or uwsgi

### ISSUE THREAD

**Issue by tassinf** [maxcountryman/flask-login#729] opened 2023-01-18 15:35 UTC
**Describe the bug**
When running my application on gunicorn or uwsgi, the first logged user is used for all subsequent requests. You're not even required to log if someone is already logged. Moreover, you'll get all his accesses. 

In my development environment (pycharm) 'g' acts like a request_context, but in production (rhel8) used with gunicorn or uwsgi 'g' acts like an app_context and isn't reset between requests. 

I fixed locally the issue replacing 'g' by 'session' in login_manager.py (line 341) and in utils.py (lines 371, 374)

**To Reproduce**
1. Used  Flask_Security_Too / FlaskSQLAlchemy to create a simple app.
2. Define a end-point that require authentication
3. Create two users
4. Run the app with gunicorn or uwsgi
5. Access the protected endpoint from two different browsers/computers and see how the two sessions interfere.

**Expected behavior**
Obviously sessions for different users shouldn't interfere.

**Desktop (please complete the following information):**
 - OS: RHEL8
 - Browser: chrome, firefox
 - Version [e.g. 22] Flask_Login: 0.6.2

**Comment by davidism** [comment] 2023-01-18 15:39
I can't reproduce this issue with the information provided. This is also a duplicate of other issues with a similar lack of reproducible example: #721, #722, #724, #728. It sounds like something else is wrong with your setup, but we can't debug that here.

**Closed by davidism** 2023-01-18 15:39 UTC

**Comment by tassinf** [comment] 2023-01-18 17:07
Here is a simplified version of my app. I'm using a virtualenv on RHEL8 with Python 3.9.13

mkdir /opt/flissue
cp flissue.zip /opt/flissue/
cd /opt/flissue/
unzip flissue.zip
virtualenv -p python3 venv
pip3 install -r requirements.txt

. venv/bin/activate
python3 -m sflask  ==> log on http://your-server with user@test.org/user or admin@test.org/admin from 2 browser ex: firefox/chrome and it will be ok.

gunicorn -b 0.0.0.0:80 sflask:app ==> log and see how the sessions interfere

[flissue.zip](https://github.com/maxcountryman/flask-login/files/10448780/flissue.zip)
[requirements.txt](https://github.com/maxcountryman/flask-login/files/10448793/requirements.txt)

**Comment by davidism** [comment] 2023-01-18 17:11
I don't see anything about Flask-Login in that example.

**Comment by tassinf** [comment] 2023-01-18 23:59
Indeed, I'm not using Flask-Login directly but Flask-Security_Too which uses Flask-Login. As far as I can check, the issue seems to be the use of the 'g' object to store the logged_user and this is not part of the Flask-Security-Too code but well part of the Flask-Login code. 

Now, you may be right, Flask-Security-Too tries perhaps to use Flask-Login beyond it's capabilities. I'll open an issue @ Flask-Security. I guess it will end here at some point maybe not as an issue but as a feature request. ;)

**Comment by tassinf** [comment] 2023-01-23 10:12
@davidism : You were right, this was my fault. Pushing an app_context and don't popping it back when my db was updated at application start-up.
