### ISSUE TITLE
logout_user not sending "samesite" property to expire remember cookie

### ISSUE THREAD

**Issue by franciscoescher** [maxcountryman/flask-login#734] opened 2023-03-23 02:25 UTC
**Describe the bug**
logout_user not sending "samesite" property to expire remember cookie, so the browser will not actually expire it when logout is an api route, and a refresh to the page will still be logged in.

**To Reproduce**
1. Prepare a login and a logout route in your backend
2. Log in to your application in a form in the frontend (must be browser, not postman or similars)
3. Log out, calling the backend route.
4. Note that the request is not using the "set cookie" and remember cookie continues live.
5. refresh the page and you will still be logged in.

**Expected behavior**
Set cookie will return the same "samesite" attribute that login

**Comment by jwag956** [comment] 2023-04-25 22:53
This appears to be a duplicate of #683 and sure seems like a pretty serious security concern (a remember cookie not being unset and the user remaining authenticated).

**Comment by maxcountryman** [comment] 2024-01-21 13:08
This issue has already been reported. If it's still an issue then please address it with a proposed fix in the form of a PR.

**Closed** 2024-01-21 13:08 UTC
