### ISSUE TITLE
Use `flask.request` instead of `flask.g` for storing `_login_user`

### ISSUE THREAD

**Issue by v01dXYZ** [maxcountryman/flask-login#751] opened 2023-06-02 10:45 UTC
Hello,

When using a flask test client, the same application context is used between different requests. This could create issue if `_login_user` depends on resources that are closed by one request.

To prevent sharing `_login_user` between requests when testing, it would be better to put in `flask.request`.

The commit introducing `g._login_user` (359fb004f153635952a7d32ded1bbd6d74ec2561) changed `_request_ctx` with `g`. However, It seems `request` better corresponds.

**Comment by davidism** [comment] 2023-06-02 14:10
Duplicate of #704, #721, #724, #728, #729

**Closed by davidism** 2023-06-02 14:10 UTC

**Comment by v01dXYZ** [comment] 2023-06-04 17:32
Thanks you for your fast reply, sorry for the duplicate question though, I should have done my homework.
