### ISSUE TITLE
werkzeug 2.2.0 breaks flask-login

### ISSUE THREAD

**Issue by brubbel** [maxcountryman/flask-login#688] opened 2022-07-23 21:12 UTC
1. Install via flask-login via pypi
2. werkzeug 2.2.0 is installed by default (pushed as of 1 hour ago)
3. import flask_login

result:
`ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/home/docker/.local/lib/python3.10/site-packages/werkzeug/routing/__init__.py)`

workaround until fix:
`python3 -m pip install werkzeug==2.1.2`
(before installing flask)

Reported before here: https://github.com/maxcountryman/flask-login/issues/686

**Comment by davidism** [comment] 2022-07-23 21:19
Duplicate of #686

**Closed by davidism** 2022-07-23 21:19 UTC

**Comment by davidism** [comment] 2022-07-25 15:16
https://pypi.org/project/Flask-Login/0.6.2/
