### ISSUE TITLE
@login_required with Flask 2.0 Async Routes, does not return a valid response

### ISSUE THREAD

**Issue by SebastianB12** [maxcountryman/flask-login#589] opened 2021-06-08 11:56 UTC
**Describe the bug**
When using @login_required with Flask 2.0 Async Routes I get an error.

**To Reproduce**
Flask 2.0.1
Werkzeug 2.0.1
Flask-Login 0.5.0

```
@api.route('/v1.0/check_async2')
async def check_async2():
	await asyncio.sleep(1)
	return "Hello"

@api.route('/v1.0/check_async3')
@login_required
async def check_async3():
	await asyncio.sleep(1)
	return "Hello"
```

**Expected behavior**
Both should return "Hello". However the second (check_async3) returns the following error:

`"TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine."`

**Comment by 1danjordan** [comment] 2021-07-07 09:31
+1 on this. Was an incredibly difficult bug to find because I thought the issue was in my async code when I was refactoring a view function from sync to async. Only discovered it by accident!

**Comment by cathaypacific8747** [comment] 2021-07-08 04:59
Same, took me a while to pinpoint the exact issue. Solved it temporarily by using
```python
from flask import current_app
from flask import current_user

@api.route('/v1.0/check_async3')
async def check_async3():
        if not current_user.is_authenticated:
            return current_app.login_manager.unauthorized()
	await asyncio.sleep(1)
	return "Hello"
```

**Comment by 1danjordan** [comment] 2021-07-08 15:04
Worked perfectly for me, thanks a million

**Comment by maxcountryman** [comment] 2021-07-28 23:09
Happy to accept PRs related to this if anyone tracks down the root cause.

**Comment by jonasps** [comment] 2021-07-29 12:18
I believe updating the way the library calls func in it's decorators from `func(*args, **kwargs)` to  `current_app.ensure_sync(func)(*args, **kwargs)`
as described here https://flask.palletsprojects.com/en/2.0.x/async-await/#extensions might be the required solution to this problem. It worked for me with this small example.

**Comment by maxcountryman** [comment] 2021-08-03 00:35
I merged #597. If no one has concerns we can do a release soon.

**Comment by SebastianB12** [comment] 2021-11-04 06:49
Could you give us an indication, when the release will happen?
Looking forward to the Async functionality :)

**Comment by andreas93j** [comment] 2021-12-16 18:02
Would be great if somebody can fix this :) 

In the meantime you folks can use my decorator

decorators.py
```python
from functools import wraps
from flask import current_app, request
from flask_login import current_user
from flask_login.config import EXEMPT_METHODS

def async_login_required(func):
    """
        # original implementation
        if request.method in EXEMPT_METHODS:
            return func(*args, **kwargs)
        elif current_app.config.get('LOGIN_DISABLED'):
            return func(*args, **kwargs)
        elif not current_user.is_authenticated:
            return current_app.login_manager.unauthorized()
        return func(*args, **kwargs)
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        if request.method in EXEMPT_METHODS:
            return current_app.ensure_sync(func)(*args, **kwargs)
        elif current_app.config.get('LOGIN_DISABLED'):
            return current_app.ensure_sync(func)(*args, **kwargs)
        elif not current_user.is_authenticated:
            return current_app.login_manager.unauthorized()
        return current_app.ensure_sync(func)(*args, **kwargs)
    return wrapper

```


Sample view
```python
import asyncio
...
from app.decorators import async_login_required
...
@bp.route("/")
@async_login_required
async def test():
    await asyncio.sleep(1)
    return "Thank you andreas93j LOL"
```

**Closed as completed** 2022-03-29 15:10 UTC
