### ISSUE TITLE
cannot import name 'url_decode' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by zidz** [maxcountryman/flask-login#771] opened 2023-10-01 13:08 UTC
Error:
    from flask_login import LoginManager
  File "/usr/lib/python3.8/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/usr/lib/python3.8/site-packages/flask_login/login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/lib/python3.8/site-packages/werkzeug/urls.py)

**Expected behavior**
Expected behavior as of this:
https://github.com/pallets/werkzeug/pull/2608

Flask-Login==0.6.2
werkzeug==3.0.0

**Comment by itchysnake** [comment] 2023-10-01 14:39
Unfortunately also having this issue

**Comment by davidism** [comment] 2023-10-01 14:39
Duplicate of #774

**Closed by davidism** 2023-10-01 14:39 UTC

**Comment by davidism** [comment] 2023-10-27 14:27
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
